#!/bin/bash
dnf update -y
dnf install -y nodejs
mkdir -p /opt/app
echo "Y29uc3QgZXhwcmVzcyA9IHJlcXVpcmUoJ2V4cHJlc3MnKTsKY29uc3QgeyBTM0NsaWVudCwgR2V0T2JqZWN0Q29tbWFuZCB9ID0gcmVxdWlyZSgnQGF3cy1zZGsvY2xpZW50LXMzJyk7Cgpjb25zdCBhcHAgPSBleHByZXNzKCk7CmNvbnN0IHMzID0gbmV3IFMzQ2xpZW50KHsgcmVnaW9uOiBwcm9jZXNzLmVudi5BV1NfUkVHSU9OIH0pOwpjb25zdCBCVUNLRVQgPSBwcm9jZXNzLmVudi5CVUNLRVRfTkFNRTsKY29uc3QgUE9SVCA9IHByb2Nlc3MuZW52LlBPUlQgfHwgMzAwMDsKCmNvbnN0IHN0cmVhbVRvU3RyaW5nID0gKHN0cmVhbSkgPT4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4gewogIGNvbnN0IGNodW5rcyA9IFtdOwogIHN0cmVhbS5vbignZGF0YScsIChjKSA9PiBjaHVua3MucHVzaChjKSk7CiAgc3RyZWFtLm9uKCdlcnJvcicsIHJlamVjdCk7CiAgc3RyZWFtLm9uKCdlbmQnLCAoKSA9PiByZXNvbHZlKEJ1ZmZlci5jb25jYXQoY2h1bmtzKS50b1N0cmluZygndXRmLTgnKSkpOwp9KTsKCmFwcC5nZXQoJy8nLCBhc3luYyAocmVxLCByZXMpID0+IHsKICB0cnkgewogICAgY29uc3QgZGF0YSA9IGF3YWl0IHMzLnNlbmQobmV3IEdldE9iamVjdENvbW1hbmQoeyBCdWNrZXQ6IEJVQ0tFVCwgS2V5OiAnc2hhcmVkLnR4dCcgfSkpOwogICAgY29uc3QgY29udGVudCA9IGF3YWl0IHN0cmVhbVRvU3RyaW5nKGRhdGEuQm9keSk7CiAgICByZXMuc2VuZChgPGgxPlZpZXdlcjwvaDE+PHByZT4ke2NvbnRlbnR9PC9wcmU+PGEgaHJlZj0iLyI+UmVmcmVzaDwvYT5gKTsKICB9IGNhdGNoIChlcnIpIHsKICAgIHJlcy5zZW5kKCc8aDE+Vmlld2VyPC9oMT48cD5ObyBmaWxlIHVwbG9hZGVkIHlldC48L3A+PGEgaHJlZj0iLyI+UmVmcmVzaDwvYT4nKTsKICB9Cn0pOwoKYXBwLmxpc3RlbihQT1JULCAoKSA9PiBjb25zb2xlLmxvZyhgVmlld2VyIGxpc3RlbmluZyBvbiAke1BPUlR9YCkpOwo=" | base64 -d > /opt/app/app.js
echo "ewogICJuYW1lIjogInZpZXdlci1hcHAiLAogICJ2ZXJzaW9uIjogIjEuMC4wIiwKICAibWFpbiI6ICJhcHAuanMiLAogICJkZXBlbmRlbmNpZXMiOiB7CiAgICJleHByZXNzIjogIl40LjE5LjIiLAogICAiQGF3cy1zZGsvY2xpZW50LXMzIjogIl4zLjYwMC4wIgogIH0KfQo=" | base64 -d > /opt/app/package.json
cd /opt/app
npm install --omit=dev
cat > /etc/systemd/system/viewer.service << 'SERVICE'
[Unit]
Description=Viewer App
After=network.target
[Service]
Environment=BUCKET_NAME=itmo-544-cesar2005-fileshare
Environment=AWS_REGION=us-east-2
Environment=PORT=3000
WorkingDirectory=/opt/app
ExecStart=/usr/bin/node /opt/app/app.js
Restart=always
User=ec2-user
[Install]
WantedBy=multi-user.target
SERVICE
chown -R ec2-user:ec2-user /opt/app
systemctl daemon-reload
systemctl enable viewer.service
systemctl start viewer.service
